# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MCEuropeanOptionPricer <- function(Expiry, Strike, Spot, Vol, r, NumberOfPaths, baseSeed) {
    .Call(`_OptionPricer_MCEuropeanOptionPricer`, Expiry, Strike, Spot, Vol, r, NumberOfPaths, baseSeed)
}

rcpp_hello <- function() {
    .Call(`_OptionPricer_rcpp_hello`)
}

squareMe <- function(x) {
    .Call(`_OptionPricer_squareMe`, x)
}

