// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// MCEuropeanOptionPricer
double MCEuropeanOptionPricer(double Expiry, double Strike, double Spot, double Vol, double r, unsigned long int NumberOfPaths, unsigned long int baseSeed);
RcppExport SEXP _OptionPricer_MCEuropeanOptionPricer(SEXP ExpirySEXP, SEXP StrikeSEXP, SEXP SpotSEXP, SEXP VolSEXP, SEXP rSEXP, SEXP NumberOfPathsSEXP, SEXP baseSeedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type Expiry(ExpirySEXP);
    Rcpp::traits::input_parameter< double >::type Strike(StrikeSEXP);
    Rcpp::traits::input_parameter< double >::type Spot(SpotSEXP);
    Rcpp::traits::input_parameter< double >::type Vol(VolSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< unsigned long int >::type NumberOfPaths(NumberOfPathsSEXP);
    Rcpp::traits::input_parameter< unsigned long int >::type baseSeed(baseSeedSEXP);
    rcpp_result_gen = Rcpp::wrap(MCEuropeanOptionPricer(Expiry, Strike, Spot, Vol, r, NumberOfPaths, baseSeed));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello
List rcpp_hello();
RcppExport SEXP _OptionPricer_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}
// squareMe
double squareMe(double x);
RcppExport SEXP _OptionPricer_squareMe(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(squareMe(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_OptionPricer_MCEuropeanOptionPricer", (DL_FUNC) &_OptionPricer_MCEuropeanOptionPricer, 7},
    {"_OptionPricer_rcpp_hello", (DL_FUNC) &_OptionPricer_rcpp_hello, 0},
    {"_OptionPricer_squareMe", (DL_FUNC) &_OptionPricer_squareMe, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_OptionPricer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
