# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_int <- function() {
    .Call(`_priceThisOption_test_int`)
}

rcpp_hello <- function() {
    .Call(`_priceThisOption_rcpp_hello`)
}

